name: functions-deployment-template

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@v0.1.0
      with: 
        path: ./package.json
        prop_path: 'version'
    - run: echo ${{steps.version.outputs.prop}}   
    

      
