name: functions-deployment-template

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: get nested property
        uses: notiz-dev/github-action-json-property@release
        id: format_script
        with: 
          path: 'package.json'
          prop_path: 'scripts.format'
      - run: echo ${{steps.format_script.outputs.prop}} 
    

      
