name: functions-deployment-template

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: '.'

jobs:
  apply:
    env:
      
      # @devsupply token
      NPM_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}
      # @nfcc-functions token
      NFCC_NPM_TOKEN: ${{ secrets.NFCC_NPM_TOKEN }}  
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/setup-node@v1

      - run: npm install
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "terraform/apply"
        
      - name: get provider
        uses: notiz-dev/github-action-json-property@release
        id: format_script
        with: 
          path: 'package.json'
          prop_path: 'functionConfig.provider'
        
      - name: AWS Terraform Apply
        if: steps.format_script.outputs.prop == 'azure'
        env:
          #AWS specific settings
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        id: init
        run: node ./node_modules/.bin/functions-bundler apply --auto-approve
