name: functions-deployment-template

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: '.'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get version
      id: version
      with: 
        path: 'package.json'
        prop_path: 'version'
    - run: echo ${{steps.version.outputs.prop}}        
    

      
